/**
 * Rust -> TypeScript API contract check, the other half of `apps/cli/tests/api_contract_fixtures.rs`.
 *
 * There is no test runner here on purpose — no vitest dependency to add, nothing to execute.
 * Every assertion below is a `satisfies` expression: TypeScript checks it at compile time, so
 * `npm run typecheck` (or `npm run build`, which runs `tsc` first) is the thing that runs this
 * file. A JSON fixture whose shape no longer matches its TS type fails typecheck right here,
 * naming the exact interface and the exact missing/mismatched field — instead of the mismatch
 * surfacing later as a blank cell or a silently-dropped value in the running dashboard, which is
 * what happened with the coverage matrix and the fleet strip (see AGENTS.md item 2).
 *
 * The fixtures are generated by the Rust side from the real response structs, not hand-written:
 *
 *   UPDATE_API_FIXTURES=1 cargo test -p agentworth-cli api_contract
 *
 * Regenerate them after any Rust change to a response type, then run `npm run typecheck` here
 * to see what the TS type needs to catch up to.
 *
 * A JSON import always types a string leaf as plain `string`, never as the literal it actually
 * holds — so `satisfies` alone fails on any field typed as a literal union on the TS side
 * (`OutcomeKind`, `EventPayload`'s `type` tag, `FileActionType`), independent of whether the
 * shape is actually right. A blanket `as Type` "fixes" that but is too permissive the other
 * way: verified below (temporarily renaming a required field on a fixture and re-running
 * `npm run typecheck` still passed under a top-level `as` cast) — TypeScript's assertion
 * compatibility check does not reliably catch a missing required property once enough other
 * properties still line up. So the handful of literal-union leaves are narrowed individually,
 * by name, with `as`; everything else is still checked with a real `satisfies`, which does
 * catch a missing or renamed field.
 */

import matrixFixture from './__fixtures__/matrix.json';
import usageFixture from './__fixtures__/usage.json';
import tracesFixture from './__fixtures__/traces.json';
import traceDetailFixture from './__fixtures__/trace_detail.json';
import traceEventsPageFixture from './__fixtures__/trace_events_page.json';
import pacingFixture from './__fixtures__/pacing.json';
import blameFixture from './__fixtures__/blame.json';
import archaeologyFixture from './__fixtures__/archaeology.json';
import scanFixture from './__fixtures__/scan.json';

import type {
  CoverageMatrixResponse,
  UsageResponse,
  SessionSummary,
  TraceDetailWireResponse,
  EventsPageResponse,
  PacingResponse,
  BlameResponse,
  ArchaeologyData,
  ScanSummary,
  OutcomeKind,
  EventPayload,
} from './index';

// No literal-union leaves in these three — a plain `satisfies` already does the full, strict
// job: every field of the type must be present, with a compatible type, or this fails.
matrixFixture satisfies CoverageMatrixResponse;
usageFixture satisfies UsageResponse;
pacingFixture satisfies PacingResponse;
archaeologyFixture satisfies ArchaeologyData;
scanFixture satisfies ScanSummary;

// `SessionSummary.primary_outcome` is the one literal-union leaf here. Narrowed by name;
// every other field (there are thirteen) is still checked by the closing `satisfies`.
tracesFixture.map((s) => ({
  ...s,
  primary_outcome: s.primary_outcome as OutcomeKind | undefined,
})) satisfies SessionSummary[];

// `BlameMatch.action` is the one literal-union leaf here (`FileActionType`, a plain string
// union, not a discriminant with a `data` payload attached -- so narrowing just this field is
// enough; nothing else about the shape depends on its value).
blameFixture.map((m) => ({
  ...m,
  action: m.action as BlameResponse[number]['action'],
})) satisfies BlameResponse;

/**
 * `NormalizedEvent.payload` is `EventPayload`, a `type`-tagged union where the `data` shape
 * itself depends on `type` -- narrowing just the `type` field the way `primary_outcome` and
 * `action` are above would still leave a `data` shape TypeScript can't line up with any single
 * union member. This casts the whole `payload` per-event instead, which gives up shape
 * verification for the *inside* of each event's payload -- everything else about the event
 * (`id`, `sequence`, `timestamp`, `raw_ref`) and everything outside `events` on the surrounding
 * response is still checked by the closing `satisfies`.
 */
function narrowEvents<E extends { payload: unknown }>(events: E[]) {
  return events.map((e) => ({ ...e, payload: e.payload as EventPayload }));
}

traceDetailFixture satisfies { events_total: number; events_offset: number };
({
  ...traceDetailFixture,
  trace: {
    ...traceDetailFixture.trace,
    events: narrowEvents(traceDetailFixture.trace.events),
  },
  outcomes: traceDetailFixture.outcomes.map((o) => ({ ...o, kind: o.kind as OutcomeKind })),
}) satisfies TraceDetailWireResponse;

({
  ...traceEventsPageFixture,
  events: narrowEvents(traceEventsPageFixture.events),
}) satisfies EventsPageResponse;
