import React from "react";
import { SiteHeader, SiteFooter, InstallLine } from "./SiteChrome";
import { DocsNav, DocsSearch, LEARN, SPECS, RESEARCH, REFERENCE_ITEMS } from "./DocsShell";
import { docPath, humanDate, reference, releases } from "../content";

const latest = releases[0];

export const DocsHomePage: React.FC = () => (
  <>
    <a className="skip" href="#main">
      Skip to content
    </a>
    <SiteHeader current="docs" />

    <main id="main">
      <div className="wrap">
        <nav className="crumbs" aria-label="Breadcrumb">
          <a href="/">Home</a>
          <span aria-hidden="true">/</span>
          <span aria-current="page">Docs</span>
        </nav>

        <header className="page-head docs-head">
          <p className="kicker">Docs</p>
          <h1>Everything AgentWorth writes down, in one place.</h1>
          <p className="lede">
            Guides for pointing it at your own history, the CLI, API and MCP reference
            generated from the binary, the specs behind every feature, the research that
            fed them, and what shipped.
          </p>
          <DocsSearch />
        </header>

        <div className="docs-layout">
          <DocsNav section="home" />

          <div className="docs-main">
            <div className="card-grid-lg">
              <a className="doc-card doc-card-lg" href={docPath("learn", LEARN[0].slug)}>
                <span className="card-top">
                  <h2>Learn</h2>
                  <span className="count">{LEARN.length} pages</span>
                </span>
                <p>
                  Install it, read the outcome ladder, and get the handoff, the asks, the
                  forgotten decisions and the suspect commits out of a session you already
                  ran.
                </p>
                <ul>
                  {LEARN.slice(0, 4).map((d) => (
                    <li key={d.slug}>{d.title}</li>
                  ))}
                </ul>
              </a>

              <a className="doc-card doc-card-lg" href="/docs/reference/">
                <span className="card-top">
                  <h2>Reference</h2>
                  <span className="count">{REFERENCE_ITEMS} entries</span>
                </span>
                <p>
                  Every command, route and tool, generated by{" "}
                  <code className="mono">agentworth docs --write</code> from v
                  {reference.version}. CI fails the build if this page would disagree with
                  the binary.
                </p>
                <ul>
                  <li>CLI &mdash; {reference.cli.length} commands</li>
                  <li>HTTP API &mdash; {reference.api.length} routes</li>
                  <li>MCP Tools &mdash; {reference.mcp.length} tools</li>
                </ul>
              </a>
            </div>

            <div className="card-grid-sm">
              <a className="doc-card doc-card-sm" href="/docs/specs/">
                <span className="card-top">
                  <h3>Specs</h3>
                  <span className="count mono">{SPECS.length}</span>
                </span>
                <p>The design doc behind every feature, each one measured before it was built.</p>
              </a>
              <a className="doc-card doc-card-sm" href="/docs/research/">
                <span className="card-top">
                  <h3>Research</h3>
                  <span className="count mono">{RESEARCH.length}</span>
                </span>
                <p>Memos that fed a spec. Every claim sourced, context-only, never a decision.</p>
              </a>
              <a className="doc-card doc-card-sm" href="/changelog/">
                <span className="card-top">
                  <h3>Changelog</h3>
                  <span className="count mono">v{latest.version}</span>
                </span>
                <p>
                  {latest.changeCount} {latest.changeCount === 1 ? "change" : "changes"} on{" "}
                  {humanDate(latest.date)}, each with the pull request behind it.
                </p>
              </a>
            </div>
          </div>
        </div>

        <section className="close-band">
          <h2>Point it at your own machine.</h2>
          <InstallLine />
        </section>
      </div>
    </main>

    <SiteFooter />
  </>
);
